- name: gather facts
  hosts: all
  tasks:
    - name: ansible host informative
      debug:
        msg: 
        - "{{ansible_distribution}}"
        - "{{ansible_os_family}}"   #here information from setup file gathered#