- name: loops in ansible
  hosts: all
  tasks:
    - name: task in ansible 
      debug:
        msg: list of cities {{item}}
      loop:
        - Nagpur
        - Mumbai
        - Pune
        - Amravati



- name: Install the latest version of Apache
   ansible.builtin.yum:
                  name: httpd
                 state: latest