- name: loops in ansible
  hosts: all
  tasks:
    - name: task in ansible 
      debug:
        msg: list of cities {{item}}
      loop:
        - Nagpur
        - Mumbai
        - Pune
        - Amravati


- name: loops in ansible
  hosts: all
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.yum:
       state: present
        name:  {{item}}
      loop:
        - httpd
        - vim
        - tree
        - java
