- name: registering vars
  hosts: all
  tasks: 
    - name: print the uptime 
      shell: uptime
      register: OUT

    - name: print out
      debug: 
        msg: "{{OUT.stdout}}"

    - name: listing 
      shell: ls
      register: WORK

    - name: print out
      debug: 
        msg: "{{WORK.stdout}}"
      