- name: variable playbook
  hosts: all  
  vars: 
    url: www.example.com
    vars_files:
     - filevars.yaml  

  tasks: 
    - name: variable print 
      debug: 
        msg: "{{url}}"
        vars: 
           url: www.local.example222.com